version: '3'
services:
  web:
    build: .
    image: flaskhello
    environment:
     - FLASK_RUN_HOST=${FLASK_RUN_HOST} 
     #- FLASK_APP=${FLASK_APP}
     - FLASK_RUN_PORT=${FLASK_RUN_PORT}
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
